//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADPUK.NINA.AddToAlignmentModel.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADPUK.NINA.AddToAlignmentModel.Locales.ViewStrings", typeof(ViewStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Alt.
        /// </summary>
        public static string ActualAlt {
            get {
                return ResourceManager.GetString("ActualAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Az.
        /// </summary>
        public static string ActualAz {
            get {
                return ResourceManager.GetString("ActualAz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Dec.
        /// </summary>
        public static string ActualDec {
            get {
                return ResourceManager.GetString("ActualDec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual RA.
        /// </summary>
        public static string ActualRA {
            get {
                return ResourceManager.GetString("ActualRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create or Add to Alignment Model.
        /// </summary>
        public static string AlignmentModelTitle {
            get {
                return ResourceManager.GetString("AlignmentModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow use with mounts other than Alt-Az. - EXPERIMENTAL USE WITH CARE.
        /// </summary>
        public static string AllowNonAltAzMounts {
            get {
                return ResourceManager.GetString("AllowNonAltAzMounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only works with AltAz mounts.
        /// </summary>
        public static string AltAzOnly {
            get {
                return ResourceManager.GetString("AltAzOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Current Position.
        /// </summary>
        public static string BtnAddCurrentLocation {
            get {
                return ResourceManager.GetString("BtnAddCurrentLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Centre Attempts.
        /// </summary>
        public static string CentreAttempts {
            get {
                return ResourceManager.GetString("CentreAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display plate solve status.
        /// </summary>
        public static string DisplayPlateSolveStatus {
            get {
                return ResourceManager.GetString("DisplayPlateSolveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure the scope is roughly pointing at the horizon due north..
        /// </summary>
        public static string EnsureNorth {
            get {
                return ResourceManager.GetString("EnsureNorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure the scope is roughly pointing at the horizon due south.
        /// </summary>
        public static string EnsureSouth {
            get {
                return ResourceManager.GetString("EnsureSouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this correct?.
        /// </summary>
        public static string IsThisCorrect {
            get {
                return ResourceManager.GetString("IsThisCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of attempts to centre.
        /// </summary>
        public static string MaxCentreAttempts {
            get {
                return ResourceManager.GetString("MaxCentreAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Elevation.
        /// </summary>
        public static string MaximumElevation {
            get {
                return ResourceManager.GetString("MaximumElevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Elevation Above Horizon.
        /// </summary>
        public static string MinElevationAboveHorizon {
            get {
                return ResourceManager.GetString("MinElevationAboveHorizon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Elevation.
        /// </summary>
        public static string MinimumElevation {
            get {
                return ResourceManager.GetString("MinimumElevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment model builder cancelled.
        /// </summary>
        public static string ModelBuilderCancelled {
            get {
                return ResourceManager.GetString("ModelBuilderCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope pre-alignment to northern horizon not confirmed.
        /// </summary>
        public static string NorthNotConfirmed {
            get {
                return ResourceManager.GetString("NorthNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Altitude Points.
        /// </summary>
        public static string NumberOfAltitudePoints {
            get {
                return ResourceManager.GetString("NumberOfAltitudePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Azimuth Points.
        /// </summary>
        public static string NumberOfAzimuthPoints {
            get {
                return ResourceManager.GetString("NumberOfAzimuthPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay before closing plate solve window (sec).
        /// </summary>
        public static string PlateSolveDelay {
            get {
                return ResourceManager.GetString("PlateSolveDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate Solve Failed.
        /// </summary>
        public static string PlateSolveFailed {
            get {
                return ResourceManager.GetString("PlateSolveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate solve failed at Az: {{Azimuth}}, Alt: {{Altitude}}.
        /// </summary>
        public static string PlateSolveFailedAt {
            get {
                return ResourceManager.GetString("PlateSolveFailedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target at RA: {{RA}}, Alt: {{Dec}} is failed..
        /// </summary>
        public static string PlateSolveFailedRADec {
            get {
                return ResourceManager.GetString("PlateSolveFailedRADec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Alignment.
        /// </summary>
        public static string PreAlignment {
            get {
                return ResourceManager.GetString("PreAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mount must be connected via CPWI.
        /// </summary>
        public static string RequireCPWI {
            get {
                return ResourceManager.GetString("RequireCPWI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope is pointing to Az: {{Azimuth}}, Alt: {{Altitude}}.
        /// </summary>
        public static string ScopeAltAzCoordinates {
            get {
                return ResourceManager.GetString("ScopeAltAzCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope not point to pole and/or horizon.
        /// </summary>
        public static string ScopeNotAtZero {
            get {
                return ResourceManager.GetString("ScopeNotAtZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separation.
        /// </summary>
        public static string Separation {
            get {
                return ResourceManager.GetString("Separation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solve Attempts.
        /// </summary>
        public static string SolveAttempts {
            get {
                return ResourceManager.GetString("SolveAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope pre-alignment to southern horizon not confirmed.
        /// </summary>
        public static string SouthNotConfirmed {
            get {
                return ResourceManager.GetString("SouthNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Alt.
        /// </summary>
        public static string TargetAlt {
            get {
                return ResourceManager.GetString("TargetAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Az.
        /// </summary>
        public static string TargetAz {
            get {
                return ResourceManager.GetString("TargetAz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target at Az: {{Azimuth}}, Alt: {{Altitude}} is below the horizon.
        /// </summary>
        public static string TargetBelowHorizon {
            get {
                return ResourceManager.GetString("TargetBelowHorizon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Dec.
        /// </summary>
        public static string TargetDec {
            get {
                return ResourceManager.GetString("TargetDec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target RA.
        /// </summary>
        public static string TargetRA {
            get {
                return ResourceManager.GetString("TargetRA", resourceCulture);
            }
        }
    }
}
